version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Asegúrate de que esta línea esté presente y correctamente configurada
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

